source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RichTimer_Example', :exclusive => true do
  pod 'RichTimer', :path => '../'
end

target 'RichTimer_Tests', :exclusive => true do
  pod 'RichTimer', :path => '../'
end
